/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClassGradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        MountainBike classUnderTest = new MountainBike();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
