/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class Oke {
    public String getGreeting() {
        return "Hello world jancookkk.";
    }

    public static void main(String[] args) {
        System.out.println(new Oke().getGreeting());
    }
}
